In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.2)

In [3]:
lr=LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9583333333333334

In [4]:
svm = SVC(gamma='auto')
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.5305555555555556

In [5]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9777777777777777

In [6]:
###========== KFOLD VALIDATION   ===============


In [7]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for i,j in kf.split([1,2,3,4,5,6,7,8,9]):
    print(i,j)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [9]:
def get_scores(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [10]:
from sklearn.model_selection import StratifiedKFold
fold=StratifiedKFold(n_splits=3)
lr_scores=[]
svm_scores=[]
rf_scores=[]

for train_index, test_index in kf.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    lr_scores.append(get_scores(LogisticRegression(solver='liblinear',multi_class='ovr'),x_train, x_test, y_train, y_test))
    svm_scores.append(get_scores(SVC(gamma='auto'),x_train, x_test, y_train, y_test))
    rf_scores.append(get_scores(RandomForestClassifier(n_estimators=40),x_train, x_test, y_train, y_test))

In [11]:
lr_scores

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [12]:
svm_scores

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [13]:
rf_scores

[0.9248747913188647, 0.9482470784641068, 0.9215358931552587]

In [14]:
# ========== CROSS VAL SCORE    FUNCTION =============

In [15]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [17]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [18]:
cross_val_score(RandomForestClassifier(n_estimators=3),digits.data,digits.target,cv=3)

array([0.71285476, 0.79632721, 0.81135225])

In [19]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)

array([0.94657763, 0.95325543, 0.92654424])

In [20]:
## =============== EXERCISE ===============

In [21]:
from sklearn.datasets import load_iris
iris=load_iris()

In [22]:
from sklearn.model_selection import cross_val_score

In [23]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target,cv=3)

array([0.96, 0.96, 0.94])

In [24]:
cross_val_score(SVC(gamma='auto'),iris.data,iris.target,cv=3)

array([0.98, 0.98, 0.96])

In [25]:
cross_val_score(RandomForestClassifier(n_estimators=3),iris.data,iris.target,cv=3)

array([0.98, 0.9 , 0.96])

In [26]:
cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target,cv=3)

array([0.98, 0.92, 0.98])